name: Semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '28 0 * * 4'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep default rules
        run: semgrep scan --config p/default --sarif --output semgrep.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
